// AUTO-GENERATED by tools/gen_nonce.py — do not edit by hand.
// This file exists solely to invalidate Zig's module cache so that
// every build recompiles the kernel from current sources.
pub const nonce: u64 = 1788018025956380500;
