#!/usr/bin/env python3
"""Regenerate the kernel build nonce so Zig always re-resolves the kernel
module graph and recompiles every source file. Zig 0.14.1 can restore
stale module objects from the cached build graph even when source files
changed; touching this generated file invalidates that cache reliably.

Called automatically from build.zig (gen_nonce step) — do not remove.
"""
import os
import time

NONCE_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)),
                          "src", "kernel", "_build_nonce.zig")

content = (
    "// AUTO-GENERATED by tools/gen_nonce.py — do not edit by hand.\n"
    "// This file exists solely to invalidate Zig's module cache so that\n"
    "// every build recompiles the kernel from current sources.\n"
    "pub const nonce: u64 = %d;\n"
) % int(time.time_ns())

with open(NONCE_PATH, "w") as f:
    f.write(content)

print("wrote %s: nonce=%s" % (NONCE_PATH, content.split("=")[1].strip().rstrip(";")))
