.section .rodata
.align 16

.global _binary_assets_wallpaper_raw_start
_binary_assets_wallpaper_raw_start:
.incbin "assets/wallpaper.raw"

.global _binary_assets_icon_folder_raw_start
_binary_assets_icon_folder_raw_start:
.incbin "assets/icon_folder.raw"

.global _binary_assets_icon_file_raw_start
_binary_assets_icon_file_raw_start:
.incbin "assets/icon_file.raw"

.global _binary_assets_icon_settings_raw_start
_binary_assets_icon_settings_raw_start:
.incbin "assets/icon_settings.raw"

.global _binary_assets_cursor_arrow_raw_start
_binary_assets_cursor_arrow_raw_start:
.incbin "assets/cursor_arrow.raw"

.global _binary_assets_font_raw_start
_binary_assets_font_raw_start:
.incbin "assets/font.raw"
